sprint 5 task
s4fonovoleg/MovieQuiz-ios pull request #3
Opened 2023-04-05 15:33 UTC by s4fonovoleg

Yandex practicum sprint 5 task

2023-04-05 18:50 UTC, protos17 requested changes

2023-04-05 18:50 UTC, protos17 commented on MovieQuiz/Models/QuizStepViewModel.swift
> +import Foundation
Если импортирован UIKit, то можно не импортировать Foundation, потому что первый содержит в себе второй

2023-04-05 18:50 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>  	@IBAction func noButtonClicked(_ sender: UIButton) {
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, 
когда они используются только внутри области объявления.

2023-04-05 18:50 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>  	@IBAction func yesButtonClicked(_ sender: UIButton) {
Здесь тоже рекомендую указать как private

2023-04-05 18:50 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +		let presenter = ResultAlertPresenter(delegate: self)
Презентер рекомендую вынести в область видимости класса наравне с фабрикой и статистик сервисом

2023-04-05 18:50 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +		message +=
Можно использовать многострочный вариант строки

2023-04-05 18:50 UTC, protos17 commented on MovieQuiz/Presentation/ResultAlertPresenter.swift
> +import Foundation
Можно убрать Foundation

2023-04-05 18:50 UTC, protos17 commented on MovieQuiz/Presentation/ResultAlertPresenter.swift
> +class ResultAlertPresenter: AlertPresenterProtocol {
Рекомендую указать как final

2023-04-05 18:50 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +class QuestionFactory : QuestionFactoryProtocol {
Рекомендую указать как final

2023-04-05 18:50 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +			text: "Рейтинг этого фильма больше чем 6?",
Этот вопрос тот же, что и константа questionText, рекомендую использовать ее

2023-04-05 18:50 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +
Рекомендую здесь добавить проверку на то, что вопрос не был показан ранее (по желанию)

2023-04-05 18:50 UTC, protos17 commented on MovieQuiz/Services/StatisticService.swift
> +			let totalAccuracy = userDefaults.double(forKey: Keys.totalAccuracy.rawValue)
Можно писать сразу "userDefaults.double(forKey: Keys.totalAccuracy.rawValue)" без введения константы. Это касается и остальных сохраненных данных в  userDefaults

2023-04-05 18:50 UTC, protos17 commented on MovieQuiz/Services/StatisticService.swift
> +				print("Невозможно сохранить результат")
Рекомендую использовать assertionFailure вместо print

2023-04-05 20:35 UTC, s4fonovoleg commented on MovieQuiz/Models/QuizStepViewModel.swift
> +import Foundation
убрал

2023-04-05 20:35 UTC, s4fonovoleg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>  	@IBAction func noButtonClicked(_ sender: UIButton) {
добавил

2023-04-05 20:35 UTC, s4fonovoleg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>  	@IBAction func yesButtonClicked(_ sender: UIButton) {
добавил

2023-04-05 20:35 UTC, s4fonovoleg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +		let presenter = ResultAlertPresenter(delegate: self)
вынес презентер

2023-04-05 20:36 UTC, s4fonovoleg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +		message +=
изменил на многострочный вариант

2023-04-05 20:36 UTC, s4fonovoleg commented on MovieQuiz/Services/QuestionFactory.swift
> +class QuestionFactory : QuestionFactoryProtocol {
добавил

2023-04-05 20:36 UTC, s4fonovoleg commented on MovieQuiz/Services/QuestionFactory.swift
> +			text: "Рейтинг этого фильма больше чем 6?",
исправил

2023-04-05 20:37 UTC, s4fonovoleg commented on MovieQuiz/Services/QuestionFactory.swift
> +
добавил массив перемешанных индексов
P.S. сначала сделал через добавление во временный массив уже показанных вопросов, но вариант, когда случайные числа генерируются пока не сгенерируется индекс вопроса, которого еще не было - мне не понравился :)

2023-04-05 20:38 UTC, s4fonovoleg commented on MovieQuiz/Services/StatisticService.swift
> +			let totalAccuracy = userDefaults.double(forKey: Keys.totalAccuracy.rawValue)
исправил

2023-04-05 20:38 UTC, s4fonovoleg commented on MovieQuiz/Services/StatisticService.swift
> +				print("Невозможно сохранить результат")
изменил

2023-04-06 21:05 UTC, protos17 approved these changes

2023-04-06 21:05 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>  	@IBOutlet weak var yesButton: UIButton!
Здесь всем переменным рекомендую указать область видимости private, даже несмотря на то, что они weak

2023-04-09 13:05 UTC, merged